### ISSUE TITLE
Following count and /following page inconsistent

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#682] opened 2017-08-18 11:08 UTC
See the screenshot below. There's an inconsistency between "Following 10" and "Decker is Not Following Anyone Yet"

![screen shot 2017-08-18 at 10 48 49](https://user-images.githubusercontent.com/731743/29453849-0216a19e-8403-11e7-8317-37b0467fdfa2.png)

**Comment by hoffmabc** [comment] 2017-08-18 11:58
We have a refactor for this coming today. Pinging @rmisio as he worked on this.

**Comment by jjeffryes** [comment] 2017-08-18 13:47
This is a duplicate of #593 and #200

**Closed by jjeffryes** 2017-08-18 13:47 UTC
Labels: enhancement
