### ISSUE TITLE
Coupon codes should not be case sensitive

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#882] opened 2017-09-15 02:02 UTC
They are not a password.

**Comment by jjeffryes** [comment] 2017-09-15 02:14
@cpacia the coupon codes have to be case sensitive because we're comparing hashes, right?

**Comment by rhcastilhos** [comment] 2017-09-15 02:20
The software should at least create hashes for the coupon code in lowercase and upercase.

**Comment by jjeffryes** [comment] 2017-09-21 14:51
This is working as intended, and we don't plan to change it, so I am closing this issue.

**Closed by jjeffryes** 2017-09-21 14:51 UTC
