### ISSUE TITLE
Client or Server Needs to Strip Extra @ Symbols from Usernames

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#509] opened 2017-06-05 14:30 UTC
![image](https://cloud.githubusercontent.com/assets/45482/26788034/ed225944-49d9-11e7-99ea-5da4cd50e95d.png)

I'm not sure who should handle it, but I'm thinking server side @cpacia. I'm posting it here because I noticed it in the UI for now.

**Comment by rmisio** [comment] 2017-06-05 16:08
The handle does not have the extra @ symbol on the server. It has only one and the client is adding the additional one. The problem is that the server is not validating the handle and it is allowing both `myhandle` and `@myhandle` to be saved.

The client then has to decide whether to preface the handle with an @ depending on whether it has one or not. In the screenshot you posted, the client is failing to do that.

It would however, simplify things here if the server could pick a lane and validate that the handle is provided in a consistent way (either a. it must be prefaced with an @ or b. it cannot be prefaced with an @).

**Comment by jjeffryes** [comment] 2017-06-05 16:15
I agree, it would be better if the server had consistent rules on handles. Otherwise all clients will have to check all handles whenever they're used to decide if they should add a @ in front of it or not.

@cpacia can we validate the handle on the server to require either an @ or not? I think not is better, since the at symbol isn't actually part of the handle.

**Comment by rmisio** [comment] 2017-06-05 17:02
I also think without the @ is better, but @drwasho will need to adjust since I'm pretty sure he's adding it in on the mobile app.

**Comment by hoffmabc** [comment] 2017-06-05 17:15
I'm sure he's ok with it. I already mentioned it and he thought server should handle it as well.

So can we do this validation @cpacia? I'll open a ticket.

**Comment by hoffmabc** [comment] 2017-06-05 17:17
Server issue is https://github.com/OpenBazaar/openbazaar-go/issues/538

**Comment by rmisio** [comment] 2017-07-12 16:24
This should be fixed by the fact that the server is fixed.

**Closed by rmisio** 2017-07-12 16:24 UTC
Labels: bug
