### ISSUE TITLE
'Uncaught Exception: RangeError: Invalid string length' after regaining lost network connection

### ISSUE THREAD

**Issue by DivineOmega** [OpenBazaar/openbazaar-desktop#953] opened 2017-09-26 21:23 UTC
Brief Description: Shortly after regaining network and Internet connectivity after a router restart, Open Bazaar showed the following error dialog.

```
A JavaScript error occurred in the main process

Uncaught Exception:
RangeError: Invalid string length
    at log (/usr/lib/openbazaar2/resources/app/mainBuilt.js:601:9)
    at LocalServer.<anonymous> (/usr/lib/openbazaar2/resources/app/mainBuilt.js:609:10)
    at triggerEvents (/usr/lib/openbazaar2/resources/app/node_modules/backbone/backbone.js:370:57)
    at triggerApi (/usr/lib/openbazaar2/resources/app/node_modules/backbone/backbone.js:356:19)
    at eventsApi (/usr/lib/openbazaar2/resources/app/node_modules/backbone/backbone.js:155:16)
    at LocalServer.Events.trigger (/usr/lib/openbazaar2/resources/app/node_modules/backbone/backbone.js:346:5)
    at LocalServer._log (/usr/lib/openbazaar2/resources/app/js/utils/localServer.js:266:12)
    at /usr/lib/openbazaar2/resources/app/js/utils/localServer.js:295:23
    at Array.forEach (native)
    at LocalServer.obServerLog (/usr/lib/openbazaar2/resources/app/js/utils/localServer.js:294:26)
```

Clicking the provider 'OK' button resulting in the dialog closing and immediately reopening. After several reopenings, the error changes to the following.

```
A JavaScript error occurred in the main process

Uncaught Exception:
RangeError: Invalid string length
    at LocalServer._log (/usr/lib/openbazaar2/resources/app/js/utils/localServer.js:265:25)
    at /usr/lib/openbazaar2/resources/app/js/utils/localServer.js:295:23
    at Array.forEach (native)
    at LocalServer.obServerLog (/usr/lib/openbazaar2/resources/app/js/utils/localServer.js:294:26)
    at Socket.<anonymous> (/usr/lib/openbazaar2/resources/app/js/utils/localServer.js:108:23)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

This message that repeated continually, and the process needed to be terminated via a `killall openbazaar2` command.

Operating System (OS and version): Ubuntu 16.04 LTS
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware: Desktop PC - ask if full specifications required.

Might be related to #949.

**Comment by rmisio** [comment] 2017-09-26 21:51
closing as dupe of #949 

(Sorry you had to re-write it in this repo. I didn't just want to close it in v1 without letting you know about v2)

**Closed by rmisio** 2017-09-26 21:51 UTC
