### ISSUE TITLE
"Pay" button sometimes gets stuck after clicking at order screen

### ISSUE THREAD

**Issue by imaginaryusername** [OpenBazaar/openbazaar-desktop#1779] opened 2019-06-23 01:19 UTC
Brief Description: 

Operating System (OS and version): Fedora 30
OpenBazaar version (shown on `About OpenBazaar` page in menu): 2.3.3/0.13.3
Hardware: x86_64 w/DDR4 on SSD

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Sometimes

Steps to reproduce:
1. Select a product to purchase 
2. Go through with filling out the order - direct payment or moderated did not seem to matter
3. Click "Pay", the button turns into a spinning wheel that never finishes

Observed Behavior:
Pay button spins and never advances to the next card where the actual payment is made.

Expected Behavior:
Order advances to the next card where payment can be made either directly via QR or from wallet.

Additional info (links, images, etc go here): Seems less prevalent on more established stores.

**Comment by jjeffryes** [comment] 2019-06-24 12:45
Thank you for opening this issue, @imaginaryusername. How long have you left the pay button loading? It's making a purchase call when it does that, sometimes that can take a minute or longer if the seller's node can't be reached.

After you see the pay button get stuck, does the order appear as unpaid in your purchases list?

**Comment by imaginaryusername** [comment] 2019-06-24 18:10
I see, so it's a "node cannot be reached" problem? I left it there for 10 minutes before cancelling. 

There now seems to be a purchase in my list I don't know what to do with =\

**Comment by jjeffryes** [comment] 2019-12-02 16:39
I'm closing this as working as intended, just very slow and a little confusing.

**Closed by jjeffryes** 2019-12-02 16:39 UTC
