### ISSUE TITLE
Attempting to checkout without a moderator, but a error message comes up saying "Moderator could not found"

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#561] opened 2017-07-12 16:51 UTC
I'm attempting to purchase this listing: ob://QmZXGKrRRe5RTDhvzhZfSTe8vYBDGV7HBoNz5FS3U9FnUa/store/test-bulk-upload

I unchecked the "Moderated payment" checkbox, yet I still get hit with the error below.

![screen shot 2017-07-12 at 9 49 05 am](https://user-images.githubusercontent.com/13066886/28129229-6ed014ac-66e7-11e7-9684-e173567c9682.png)

![screen shot 2017-07-12 at 9 49 01 am](https://user-images.githubusercontent.com/13066886/28129268-8ec23bbe-66e7-11e7-8478-a4bab3aab8e0.png)

**Comment by jjeffryes** [comment] 2017-07-12 17:21
I can't reproduce this one either. I was able to order the same listing without a moderator.

**Comment by jjeffryes** [comment] 2017-07-20 19:01
@morebrownies did you ever see this bug again?

**Comment by morebrownies** [comment] 2017-07-20 22:28
Nope, haven't seen it again on my end.

**Comment by jjeffryes** [comment] 2017-07-20 22:49
I'm closing this as not an issue we can reproduce.

**Closed by jjeffryes** 2017-07-20 22:49 UTC
Labels: bug
