### ISSUE TITLE
Chat Emoji Causes Borking

### ISSUE THREAD

**Issue by jashot7** [OpenBazaar/openbazaar-desktop#794] opened 2017-09-07 04:04 UTC
On Mac, open the character viewer with command-control-space and enter non standard characters. Its easy to bork chat by entering them.

![sep-07-2017 00-03-13](https://user-images.githubusercontent.com/392798/30145551-fae294ac-935f-11e7-8fd0-511799d50854.gif)

**Comment by rmisio** [comment] 2017-09-07 18:35
@jashot7 Is there a specific emoji you are using to cause this? I've tried a bunch of them (including some seemingly obscure ones) and I can't reproduce this.

@morebrownies Fellow OSser, does this happen for you?

**Comment by hoffmabc** [comment] 2017-09-07 18:36
i haven't found one that does it

**Comment by jjeffryes** [comment] 2017-09-08 00:26
We determined that this bug wasn't related to chat emojis, I'm going to close it until we can reproduce it and/or figure out what it was.

**Closed by jjeffryes** 2017-09-08 00:26 UTC
Labels: bug, Medium Priority
