### ISSUE TITLE
Incoming transaction allows me to retry payment

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#607] opened 2017-08-04 14:40 UTC
I don't believe this should be showing for incoming payments.

This is on v2.0.5

![image](https://user-images.githubusercontent.com/45482/28973470-4cab6a58-7901-11e7-9f7e-ef7132493495.png)

**Comment by rmisio** [comment] 2017-08-04 15:12
When a transaction is stuck (i.e. has been unconfirmed for a certain period of time -I believe the server has it at 6 hours), this is a way that the recipient can help it along by bumping the fee. This is a functionality the Bitcoin api offers and we're making it available to the user. I think the idea is that the transaction may be stuck because the sender did not give a sufficient fee and this is a way the recipient can aid the process.

Closing this as working as designed. If my understanding is not correct, we'll re-open.

**Closed by rmisio** 2017-08-04 15:12 UTC
Labels: bug
