### ISSUE TITLE
Hide Follow button on own User Card

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#358] opened 2017-02-09 19:39 UTC
![image](https://cloud.githubusercontent.com/assets/794517/22799887/4a0e5276-eebc-11e6-9bfd-28e2cfaf3ef4.png)

Rather than just being a no-op, the Follow button should, IMHO, be hidden on your own user card.

**Comment by morebrownies** [comment] 2017-02-17 17:53
+1

**Comment by morebrownies** [comment] 2017-02-17 20:08
This is actually a duplicate of #106

**Comment by jjeffryes** [comment] 2017-02-17 21:05
Closing as a duplicate.

**Closed by jjeffryes** 2017-02-17 21:05 UTC
