### ISSUE TITLE
Add "Idle" feature

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/openbazaar-desktop#367] opened 2017-02-17 16:41 UTC
This is low priority.

The client should be able to detect when it's not being used and enter an "Idle" mode. In this mode it should not make exchange price calls and possibly other calls as well.

**Comment by rmisio** [comment] 2017-02-20 16:01
Gonna close this one as a dupe of #263. We can already detect when there is not a server connection and, in this case, any server calls on a timer should not be made.

**Closed by rmisio** 2017-02-20 16:01 UTC
Labels: enhancement
