### ISSUE TITLE
Setup selecting base currency does not have GBP ... and should also show currency codes for all

### ISSUE THREAD

**Issue by ronohara** [OpenBazaar/openbazaar-desktop#1354] opened 2018-05-16 04:26 UTC
Brief Description: 

Operating System (OS and version): Linux Mint 18.3 (Linux 4.13.0)
OpenBazaar version (shown on `About OpenBazaar` page in menu): 2.2.0 - but can not get the About box at this piont of the install
Hardware: HP Omen 17

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Install
2. On the 'set your information' dialogue, select location as United Kingdom Great Britain
3. Try to find base currency GBP under any name or description in drop down

Observed Behavior:
GBP not present

Expected Behavior:
GBP present (and it would help if all the other entries included ISO currency codes)

Additional info (links, images, etc go here):

![temp5](https://user-images.githubusercontent.com/4027321/40096622-946abcf6-58c9-11e8-86e4-26f8696281de.jpg)

**Comment by BazaarDog** [comment] 2018-05-16 10:12
GBP is under "Pound Sterling", it might be clearer to have the 3 letter codes next to the currency name.

**Comment by rmisio** [comment] 2018-05-22 11:43
@morebrownies What do you think of this? Should we add the 3 letter code to the UI?

I believe we can make the drop down searchable by both the long text and code irrespective of whether we actually display the code in the UI (but that wouldn't help with the confusion of this user not realizing GBP maps to Pound Sterling).

**Comment by jjeffryes** [comment] 2018-05-22 16:41
This is mostly a duplicate of #1032, if this gets closed that should be closed too.

**Comment by morebrownies** [comment] 2018-05-22 17:40
Agreed with @jjeffryes. I have a comment on #1032 that is still accurate.

**Closed** 2018-08-14 18:36 UTC
