### ISSUE TITLE
Eth-Precision Order Details Payment Link is Invalid

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1820] opened 2019-10-24 16:39 UTC
The payment link in the order details only contains the tx, and is missing the url.

This is what I'm seeing:
```
<a class="clrT2 js-txidLink" href="">5c99ecd27a5801bae2d16614a338b11f51112871038e07b3b2994becb891ec81</a>
```

It should be like this:
```
<a class="clrT2 js-txidLink" href="https://blockchair.com/litecoin/transaction/cabdcb4862ac45335c738c2e52c3b7370c7023d265888217645b697f8584a595">cabdcb4862ac45335c738c2e52c3b7370c7023d265888217645b697f8584a595</a>
```

![image](https://user-images.githubusercontent.com/1584275/67506503-25507f00-f65b-11e9-94f3-e5b07e08a017.png)

**Comment by jjeffryes** [comment] 2019-10-28 15:14
Just to be extra clear, the transaction with the missing link was in LTC. This issue seems to affect all coin types.

**Comment by rmisio** [comment] 2019-10-28 18:00
fixed via `dffb5cd0208efe1c8cd7101b114fa73dfad142cd`.

**Comment by jjeffryes** [comment] 2019-10-28 18:47
For ETH payments, I'm getting links like 
https://blockchair.com/ethereum/transaction/15d731df5a86002b97ea975d30751a5eab2556664e0168fad7995df55e9e50b8

Which just show "status code 400"

@placer14 @cpacia should the tx we get for ETH payments be something that can be looked up?

**Comment by placer14** [comment] 2019-10-28 18:58
Based on prior conversations, I believe those txids only work after they have been mined into the ETH blockchain. I'll ask @amangale.

**Comment by drwasho** [comment] 2019-10-28 22:01
@jjeffryes @placer14 a few things:

1. The txid needs a prefix of `0x` to be detected in search with Blockchair; no such prefix is needed with etherscan.io, as it puts it in there for you (which is the industry standard for block exploring ETH transactions). Either way, you'll find the transaction https://blockchair.com/ethereum/transaction/0x15d731df5a86002b97ea975d30751a5eab2556664e0168fad7995df55e9e50b8 or https://etherscan.io/tx/0x15d731df5a86002b97ea975d30751a5eab2556664e0168fad7995df55e9e50b8

2. We can either enforce the `0x` prefix in the server or client, so I'll ask @amangale how straightforward it is to add the prefix in the server.

3. txids work before they've been mined, you just need to use the correct endpoint to fetch 'pending' transactions (equivalent of unconfirmed transactions). Unfortunately, there's been a misunderstanding that ETH doesn't show txids until after they've been mined, which isn't true. The problem has been the endpoint being used to detect a transaction (with all the metadata we want), which doesn't return pending transactions until they're confirmed/mined. The guts of #1783 and #1420 is to work around the limitations of the endpoint we were using, and use something else that helps us detect pending transactions along with some metadata that we also need.

**Comment by placer14** [comment] 2019-10-28 22:26
Re 2: I've asked @amangale to to not express the prefix internally on txids or addresses because it appeared to be a presentation detail. I recall some places do not use the prefix and some places do. Find a nice way to keep it consistent in both cases would be ideal.

Re 3: Not sure which items you're referring to with 1783 and 1420. My thinking here is that `GET /wallet/transaction` should understand the tx state and make the correct call for the client in the background. This also further blurs the clarity around what the API endpoint means for ETH (as far as ob-go configuration is concerned considering some ETH calls go to etherscan and some to infura. Having a configurable API endpoint for the ETH wallet may be a "lie" and our interface doesn't really account for that "lie" yet.)

**Comment by drwasho** [comment] 2019-10-28 22:33
>  I've asked @amangale to to not express the prefix internally on txids or addresses because it appeared to be a presentation detail. I recall some places do not use the prefix and some places do. Find a nice way to keep it consistent in both cases would be ideal.

That prefix needs to be expressed as it is used everywhere in ETH, otherwise we have problems described in this issue.

> Re 3: Not sure which items you're referring to with 1783 and 1420. 

I'm referring to the fact that the endpoint used to detect ETH transactions, data from which we use in the API responses for `POST /ob/orderspend` etc, only returns data from confirmed ETH transactions and not pending ETH transactions. Part of the work required in #1783 and #1420 is determining an alternative endpoint, from either INFURA or Etherscan, that returns pending and confirmed transactions.

**Comment by rmisio** [comment] 2019-10-28 23:09
FWIW, in the `ob/purchase` response it is included. It's not a huge deal for clients to add it, but the server IMHO should definitely be consistent.

`"paymentAddress": "0x1d4DD6A3C54F705E30E5015Fae32338925e77954"`

**Comment by drwasho** [comment] 2019-10-28 23:12
Agreed. Every other app using Ethereum uses the prefix, so let's make the server internal and externally consistent. FYI @amangale

**Comment by rmisio** [comment] 2019-12-03 19:49
This fix has already been merged into `ethereum-master`.

**Closed by rmisio** 2019-12-03 19:49 UTC
Labels: Ethereum, bug
