### ISSUE TITLE
Chat unread indicator doesn't go away after opening conversation

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#847] opened 2017-09-12 00:20 UTC
![ezgif com-video-to-gif 8](https://user-images.githubusercontent.com/13066886/30302370-6b13e808-9715-11e7-9e52-bb5b91e651bb.gif)

**Comment by jjeffryes** [comment] 2017-09-12 00:45
This is a duplicate of #703

**Closed by jjeffryes** 2017-09-12 00:45 UTC
Labels: bug
