### ISSUE TITLE
Warn of known incompatibilities between client versions

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#738] opened 2017-08-30 09:46 UTC
A buyer visiting a store with an incompatible version may not know until quite late in the purchase flow that the transaction cannot be completed. I suggest being more upfront about versioning, displaying a message like "Your OpenBazaar client has version XXX which is known to be incompatible with this node's version YYY."

This would be especially easy to do with [Semantic Versioning](http://semver.org/) (where only MAJOR versions have incompatible changes), but unfortunately I don't think we're using Semantic Versioning.

**Comment by jjeffryes** [comment] 2017-08-30 14:41
This is a duplicate of #578, we're planning to implement this, probably post 2.0.

**Closed by jjeffryes** 2017-08-30 14:41 UTC
