### ISSUE TITLE
UI enhancement - Tabs

### ISSUE THREAD

**Issue by premek** [OpenBazaar/openbazaar-desktop#1129] opened 2017-11-30 21:56 UTC
Brief Description: 
Introduce tabs to the UI like in a browser. (middle click / ctrl+click opens a new tab, ctrl+T, etc...)
Make settings, wallet etc a page in a tab, not a popup

Observed Behavior:
- cannot open multiple listings / stores / search results
- going to Settings and pressing "back" is confusing

**Comment by rmisio** [comment] 2017-11-30 22:51
duplicate of #891

**Closed by rmisio** 2017-11-30 22:51 UTC
