### ISSUE TITLE
Bug: Pressing tab on a dropdown option

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-desktop#191] opened 2016-12-12 23:21 UTC
**Brief Description**

Pressing tab on a drop-down option (e.g. in the 'create listing' modal) doesn't select that option... instead, the field is cleared.

**Operating System (OS and version):**

MacOS 10.12.1

**OpenBazaar version:** 

**Hardware:**

Macbook Pro 2016

**Reproducible:** 

Reproducible.

**Steps to reproduce:**
1. Select 'create listing'
2. Start typing the name of a country, wait until the country you want is select, and press tab
3. Allow fury to set in

![image](https://cloud.githubusercontent.com/assets/3887694/21120932/6cf15fc4-c115-11e6-940e-f0ea11202f87.png)

**Comment by rmisio** [comment] 2016-12-13 00:41
What are you expecting? The focus tabs to the next field and ay current entry you're typing ('d' in this case) is abandoned?

**Comment by hoffmabc** [comment] 2016-12-13 01:03
Enter selects the item not tab I believe @drwasho

**Comment by jjeffryes** [comment] 2016-12-13 03:12
We can add token separators, like commas. I'm not sure about tabs.

**Comment by drwasho** [comment] 2016-12-13 23:36
@rmisio the screenshot was to show where this was happening, ignore the actual input field

@hoffmabc @jjeffryes in my experience it is generally expected practice that you can select an item by pressing tab (as well as enter) in an input field that also accepts text. Right now it just clears my selection, which is very annoying. We have an inconsistent UX in 1.0 where pressing tab to select an item works (i.e. 'Ships From') and doesn't work (i.e. 'Ships To')... I'd have to check but I think pressing tab to select works for onboarding.

**Comment by jjeffryes** [comment] 2016-12-14 01:33
v1 uses the Taggle library, which allows us to use tab to set tags. but doesn't have the combination tags and select box behavior in the designs. 

In v2 we've been using select2, which does allow the combo tags and select box behavior, but has some other limitations.

**Comment by drwasho** [comment] 2016-12-14 04:46
Does `select2` support selecting a dropdown item by pressing tab?

**Comment by jjeffryes** [comment] 2016-12-14 13:54
I'm not sure. I know it can pick up specific characters, like comma, we haven't tried tabs yet.

**Comment by jjeffryes** [comment] 2017-02-28 19:58
This is a partial duplicate of #211

**Comment by rmisio** [comment] 2017-07-12 17:02
this was fixed.

**Closed by rmisio** 2017-07-12 17:02 UTC
Labels: bug
