### ISSUE TITLE
Old sales in Store reputation don't display title correctly and don't load thumbnail

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1445] opened 2018-07-15 19:39 UTC
OB v.2.2.1 Win 7 64 bits and Ubuntu 16.04 64 bits

Old sales in store reputation page (since ~Apr 2018) don't display title correctly (symbols like "-" and "&" are hidden) and don't load thumbnail, even though their URL are correct.

Example in ob://QmcUDmZK8PsPYWw5FRHKNZFjszm2K6e68BQSTpnJYUsML7/reputation:
![image](https://user-images.githubusercontent.com/10789865/42737643-243204b6-8877-11e8-9303-1b713d4c4348.png)

**Comment by hoffmabc** [comment] 2018-07-15 19:42
I think those are actually different products with inconsistent titles.

**Comment by rhcastilhos** [comment] 2018-07-15 19:43
All those items point to the same listing: ob://QmcUDmZK8PsPYWw5FRHKNZFjszm2K6e68BQSTpnJYUsML7/store/openbazaar-friends-t-shirt.

**Comment by hoffmabc** [comment] 2018-07-15 19:52
I would expect the image hash to be the same in the review. Hmm have you looked at the content of the reviews in the inspector?

**Comment by hoffmabc** [comment] 2018-07-15 19:53
It might have been a bug we fixed since after the April one the reviews look proper.

**Comment by rhcastilhos** [comment] 2018-07-15 20:03
The correct one has: 
`background-image: url(http://localhost:4002/ob/images/zb2rhhsbti96cPPsq32JUUvwcL87GU1JJSJgUf1vuoFBfSkXi), url('../imgs/defaultItem.png')`

The wrong one has:
`background-image:
url(),
url('../imgs/defaultItem.png')`

It is strange that the title is also not correct.

**Comment by cpacia** [comment] 2018-07-15 20:58
Previously reviews did not include thumbnails. That was added sometime this year if I'm correct. We can't really go back and add thumbnails to old reviews as it would break the signature on the review. 

Not sure about the title, but it's likely the same thing. Would break the signature to change the data.

**Comment by rmisio** [comment] 2018-07-18 22:05
Closing this as not a bug. Looks like we changed how the data is being stored, but that is not a retroactive thing.

**Closed by rmisio** 2018-07-18 22:05 UTC
