### ISSUE TITLE
Listing not found screen needs to be designed

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#174] opened 2016-12-07 00:04 UTC
Currently it leads you to a ~~dead end~~ less than ideal experience. The only way out is to click the back button in the navigation bar. 

![screenshot 2016-12-06 16 02 59](https://cloud.githubusercontent.com/assets/13066886/20949306/812f3fee-bbcd-11e6-9210-d37f3ce368e5.png)

**Comment by rmisio** [comment] 2016-12-07 00:33
How is that a dead end? You can navigate back, you can enter a different url in the address bar, you could use the nav menu in the top bar.

I definitely agree that the design could use some sprucing up, but to keep things simple I'm not sure how much interactivity the page needs. (I guess my concern is that dev cycles are being spent on things that arguably aren't as critical as other things, like server-connecting, ordering, search, channels, etc...)

**Comment by morebrownies** [comment] 2016-12-07 00:53
Yes, you're right. There is more than one way out. My choice of terminology could have been better. 

I have a few questions though...
Shouldn't "Listing not found" display in a modal? We open working listings in modals, so I don't really understand the inconsistency here? Moving to a modal would provide 3 additional ways to exit. Is that difficult to do?

**Comment by morebrownies** [comment] 2016-12-07 01:12
Here's what I'm thinking. We could ditch the extra reload/cancel buttons if it's time consuming. 
 
![screenshot 2016-12-06 17 09 22](https://cloud.githubusercontent.com/assets/13066886/20950819/cebd58aa-bbd6-11e6-8079-8fb79045a0b9.png)

**Comment by rmisio** [comment] 2016-12-07 16:04
> Shouldn't "Listing not found" display in a modal? We open working listings in modals, so I don't really understand the inconsistency here?

I guess we were being consistent with the other 'Not Found' pages ('user not found', 'page not found'...). Also, I suppose we were taking the lower hanging fruit, since it's debatable whether the experience is that much better the other way.

>  Is that difficult to do?

It is much more complex than a regular page. There are some hoops to jump through to make modals work with the history state. For example, when the modal is closed, you want to set the url to be to whatever it was before the modal was opened.

And... it's not prefect. For example, this is how the Listing Details modal works:

1. Load some non-store page, like Connected Peers.
2. Load store listing A. Listing A opens in modal with the Store behind it.
3. Hit Back. You land back on number 1.
4. Hit Forward. You land back on number 2.

That kind of works as expected. Perhaps in step 3, you'd rather land on the Store. But, that would require quite a hack to do. To continue:

5. With Listing A still open in a modal... you press the X to close it. The url changes to the Store and the modal closes.
6. Press forward. Nothing happens. Once we update page nav, forward will actually be disabled at this point since you're at the end of the history queue.

The issue is that in step 5, we just closed the modal and updated the url. We didn't actually navigate back in the browser's history state. The main reasons for that is:

- If we go back via the router, the whole Store will be reloaded with any previous state lost. That defeats a big purpose of the modal where you want to be able to view listings, but keep your place in the store.

@jjeffryes and I brainstormed if there was a way to go back in history without reloading the page and the only thing we could come up with we decided against because it's quite a hack and could be quite difficult to manage... and that is we turn off our router, navigate back so we go back one state in History and then after closing the modal we turn back on the router. Not even sure if that would work since turning back on the router may cause the page to reload anyway.

Another complexity along these line is what if the listing is the url that's first opened when the app is opened. There is no previous url, so I guess in that case we'd need to make this modal follow suit with the Listing Details modal and open up Listing Not Found with a certain page behind it (Store in this case).

We can't just make a generic Listing Not Found experience that works for Stores, Channels, Search.

Anyhow, some of these pain points might be able to be worked around, but they take time and / or questionable code approaches. Also, when it comes to History state, we are at the whims of the browser API, which is restrictive for security reasons.

My main point is, from a priority perspective, where should we be focusing our efforts. If this is a high priority given the complexities I described above, then so be it.

**Comment by morebrownies** [comment] 2016-12-07 17:01
> It is much more complex than a regular page. There are some hoops to jump through to make modals work with the history state. For example, when the modal is closed, you want to set the url to be to whatever it was before the modal was opened.
> 
> And... it's not prefect. For example, this is how the Listing Details modal works:
> 
> Load some non-store page, like Connected Peers.
> Load store listing A. Listing A opens in modal with the Store behind it.
> Hit Back. You land back on number 1.
> Hit Forward. You land back on number 2.
> That kind of works as expected. Perhaps in step 3, you'd rather land on the Store. But, that would require quite a hack to do. To continue:
> 
> With Listing A still open in a modal... you press the X to close it. The url changes to the Store and the modal closes.
> Press forward. Nothing happens. Once we update page nav, forward will actually be disabled at this point since you're at the end of the history queue.
> The issue is that in step 5, we just closed the modal and updated the url. We didn't actually navigate back in the browser's history state. The main reasons for that is:
> 
> If we go back via the router, the whole Store will be reloaded with any previous state lost. That defeats a big purpose of the modal where you want to be able to view listings, but keep your place in the store.
> @jjeffryes and I brainstormed if there was a way to go back in history without reloading the page and the only thing we could come up with we decided against because it's quite a hack and could be quite difficult to manage... and that is we turn off our router, navigate back so we go back one state in History and then after closing the modal we turn back on the router. Not even sure if that would work since turning back on the router may cause the page to reload anyway.
> 
> Another complexity along these line is what if the listing is the url that's first opened when the app is opened. There is no previous url, so I guess in that case we'd need to make this modal follow suit with the Listing Details modal and open up Listing Not Found with a certain page behind it (Store in this case).

Thank you for the detailed response @rmisio. I totally understand that loading listings in modals is complex, but the complexities you pointed out seem _mostly_ associated to modals in general, and not specifically to the change I'm suggesting. There is definitely some extra work here, but it's still not clear to me how much additional work is required.

> My main point is, from a priority perspective, where should we be focusing our efforts. If this is a high priority given the complexities I described above, then so be it.

I'll let @hoffmabc take that one. I share the same concerns, but at the same time, I need to be able to log issues without receiving push back. I never stated this issue was high priority, and if the issues I'm finding are overly labor intensive, let's at the minimum put a list of technical requirements on them and circle back to them later.

**Comment by jjeffryes** [comment] 2016-12-07 18:44
I don't think Rob was saying we shouldn't make the not found appear in a modal, we was saying we should prioritize it after milestone 1. 

Which I think is reasonable. Most of the other recent issues we've been filing have been things to fix before milestone 1, which made it unclear what the priority here was.

**Comment by rmisio** [comment] 2016-12-07 19:56
> if the issues I'm finding are overly labor intensive, let's at the minimum put a list of technical requirements on them and circle back to them later.

That's what I attempted to do :) I'm sorry if it was too long winded and came off as stand-offish.

> we was saying we should prioritize it after milestone 1.

Yeah, kind of. I was essentially questioning, what would we rather have first: a v2 app where you could search for listings and buy them albeit with a Listing Not Found page -or- a v2 app with a Listing Not Found modal, but no way to search for or buy a listing?

> There is definitely some extra work here, but it's still not clear to me how much additional work is required.

Not sure exactly, my best guess would be 4 hours. The wild-card is that then the Listing Not Found modal cannot be generically used for Search, Channel, etc... It would have to be created for those as well, which is some work (although it would be less than 4 hours since we could re-use some code once we make it for the store).

**Comment by morebrownies** [comment] 2016-12-07 20:31
Thank you

**Comment by jjeffryes** [comment] 2017-02-02 20:28
![image](https://cloud.githubusercontent.com/assets/1584275/22567007/2ae8dfb6-e95c-11e6-983c-28b8b3cb36d9.png)

@morebrownies  We have the above implemented now instead of a modal, is there a reason to switch to a modal? The current implementation seems ok to me.

**Comment by hoffmabc** [comment] 2017-02-02 20:34
This UI area seems so foreign when you come across it. I'm not sure if it's just the cryptic, techie explanation or not, but it just feels like it breaks the flow of the app for some reason.

**Comment by rmisio** [comment] 2017-02-02 20:39
This bug is about the Listing (singular) not found experience. Josh posted a screenshot of the Listings (plural) not found experience.

The singular one, I've already given my analysis.

The plural one I think is fine other than the specific text, which like almost all back-end errors is cryptic as heck. To fix it, we either ask the back-end to send a more usable error message or they send a unique error code along with the cryptic message, so the UI could display a more readable message. Based on past conversations, I think the server devs would be open to the latter (and probably not the former).

**Comment by morebrownies** [comment] 2017-02-02 20:56
> This bug is about the Listing (singular) not found experience. Josh posted a screenshot of the Listings (plural) not found experience.

+1 we're mixing issues here. The original issue for a listing not found still needs to be fixed imo.

> The plural one I think is fine other than the specific text, which like almost all back-end errors is cryptic as heck. To fix it, we either ask the back-end to send a more usable error message or they send a unique error code along with the cryptic message, so the UI could display a more readable message. Based on past conversations, I think the server devs would be open to the latter (and probably not the former).

+1 I have no idea what that error message means. I see it pretty often too which makes things even worse.

**Comment by jjeffryes** [comment] 2017-02-02 21:08
My bad, got my issues mixed up.

So the singular listing not found is still an issue.

**Comment by rmisio** [comment] 2017-09-20 16:12
This was completed.

**Closed by rmisio** 2017-09-20 16:12 UTC
Labels: enhancement
