### ISSUE TITLE
Wallet doesn't update confirmations

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#606] opened 2017-08-03 01:30 UTC
v2.0.5 Win10 64 bits

I've sent some testnet coins to my wallet and after 4 confirmations the wallet still show 0 confirmations, even after refreshing the page and restarting OB.

![testnetwallet](https://user-images.githubusercontent.com/10789865/28901886-bda5db02-77d1-11e7-96ec-c850cc49d13a.png)

**Comment by jjeffryes** [comment] 2017-08-03 02:36
Testnet has been very flaky. @cpacia would that be the most likely explanation here?

**Comment by rhcastilhos** [comment] 2017-08-04 04:02
Got another related error. Besides not receiving the testnet coins, after some time a retry payment button appears, but I've never done any payment on this wallet.

![wallet retry](https://user-images.githubusercontent.com/10789865/28953699-512f9e60-78b0-11e7-8d93-a6773e22fa7d.png)

**Comment by rmisio** [comment] 2017-08-04 15:13
The try buttons appears when a transaction is stuck (i.e. has been unconfirmed for a certain period of time -I believe the server has it at 6 hours). It's a way that the recipient can help it along by bumping the fee. This is functionality that the Bitcoin api offers and we're making it available to the user. I think the idea is that the transaction may be stuck because the sender did not give a sufficient fee and this is a way the recipient can aid the process. Of course, in this case it may also be stuck because Testnet has been flaky.

**Comment by rhcastilhos** [comment] 2017-08-04 15:28
It doesnt make sense. It is asking for the receiver to pay a fee to receive his money. But the receiver has 0 btc in his wallet.

**Comment by rmisio** [comment] 2017-08-04 15:37
That's a good point. I'm pretty sure if you hit Send, it would give you an error that you have insufficient funds. I suppose it would be better to hide the Retry button if there are no funds in the wallet.

**Comment by jjeffryes** [comment] 2017-08-04 16:48
I created an issue to make the text more clear and not show the retry option if the user doesn't have enough funds at #608

**Comment by jjeffryes** [comment] 2017-08-07 18:49
Closing this issue as the action items are tracked in other issues.

**Closed by jjeffryes** 2017-08-07 18:49 UTC
