### ISSUE TITLE
Clicking follow/unfollow many times results in error

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#631] opened 2017-08-07 18:25 UTC
Perhaps we should disable the button while it's waiting to return?

![image](https://user-images.githubusercontent.com/45482/29040235-3f9610fc-7b7c-11e7-8639-36d2626aa96c.png)

**Comment by rmisio** [comment] 2017-08-07 18:26
Closing as an indirect duplicate of:
https://github.com/OpenBazaar/openbazaar-desktop/issues/605

**Closed by rmisio** 2017-08-07 18:26 UTC
Labels: bug
