### ISSUE TITLE
Closing the "1 new transaction" alert within the Wallet makes it very difficult to see new transactions later on

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#674] opened 2017-08-16 18:45 UTC
I noticed in one of @SamPatt user testing videos that the user closed the "1 new transaction" alert, and then later didn't know how to see his new transactions.

![screenshot 2017-08-16 11 33 59](https://user-images.githubusercontent.com/13066886/29379331-f62c6c7a-8276-11e7-8abb-54f01624cfcc.png)

This leads to a UX issue: it's very difficult to see new transactions after the alert is closed. I believe the only way to see them is by waiting for another transaction to come through, and then clicking `refresh` on the alert.

Here's 2 solutions on how we could fix this issue:

1) Remove the `close` action on the new transaction alert. The alert will purposely annoy users until they click `refresh`. 

2) Keep the new transaction alert exactly as it is (with the close button), but each time the Wallet is opened, automatically pull in new transactions. 

I'm thinking 1 would be easier. 

Thoughts?

**Comment by jjeffryes** [comment] 2017-08-16 18:51
Isn't this true for all situations where a refresh message shows up? Maybe it should never have a close button?

The user can refresh the page they're on with the refresh button in the nav bar, but if they get rid of the refresh message they may forget they need to do that.

**Comment by morebrownies** [comment] 2017-08-16 18:55
> Isn't this true for all situations where a refresh message shows up? 

no I don't believe so. The `refresh` button in the address bar reloads your store or a listing when clicked, but it doesn't reload the Wallet when clicked. This is what leads to the problem in the Wallet. There is no other way to pull in new transactions.

**Comment by morebrownies** [comment] 2017-08-16 19:08
That raises a good point though that the `refresh` button in the address bar should probably refresh the Wallet when it's clicked. 

I know @rmisio mentioned there is some challenges in getting this to work correctly, but it's something we'll want to fix at some point.

**Comment by jjeffryes** [comment] 2017-08-16 19:15
I see. If the only situation where the nav refresh won't refresh the state but the refresh message link will is the wallet, then taking the refresh close button away from that instance of the message would probably be the simplest way to fix it.

I think it would be ok to take the close button off of all the refresh messages too, since it seems like you'd almost never want to close it instead of refreshing.

**Comment by rmisio** [comment] 2017-08-16 19:20
> That raises a good point though that the refresh button in the address bar should probably refresh the Wallet when it's clicked.

I think what I could do is probably make the transaction list refresh any time the wallet is opened.

> I know @rmisio mentioned there is some challenges in getting this to work correctly, but it's something we'll want to fix at some point.

The issue is that the wallet is not in the url. When you click refresh, you're just reloading that url (i.e. you're refreshing the underlying page) and the result is you land on that page with the wallet closed.

It's a similar thing with the Settings modal (or any modals that we don't want to be in history and we want the ability to be to open it over any page). The way to refresh Settings is by closing and re-opening it.

It's a really huge ask to say we don't want this thing in history, but when you click refresh we actually want this refreshed, not the url.

**Comment by jjeffryes** [comment] 2017-08-16 19:30
> It's a really huge ask to say we don't want this thing in history, but when you click refresh we actually want this refreshed, not the url.

I keep forgetting the wallet is a modal, it feels like a page to me. 

I don't think we need to worry about wiring it to the page nav refresh. As long as there's some way to update it.

Though I still like taking all the close buttons off the refresh messages. The fact that what the user is looking at is out of date shouldn't go away.

**Comment by morebrownies** [comment] 2017-08-16 19:30
Ok, well let's wait and see if more users get hung up by this. I'm pushing for the easy solution right now. No need to go down a rabbit hole yet.

**Comment by rmisio** [comment] 2017-08-16 19:34
ok, well getting rid of that 'X' is a few minute fix, so let's go with that for now.

@morebrownies Do you want it applied to all pop in messages or just the wallet. The only reason I'm slightly hesitant on all is because some pages have multiple pop-in messages which stack up vertically on each. It may get annoying for the user... then again that would probably be a bigger incentive to refresh. <-- I dunno, let me know.

**Comment by morebrownies** [comment] 2017-08-16 19:55
Yeah let's see.. So the point of the pop in messages is to encourage people to refresh when new content comes in. Not having the ability to close may annoy some people, but again, we're trying to encourage people to look at the freshest data.

Having the close action in place may also lead to people automatically dismissing them before reading too.

I'd be cool with ditching the close action on all of them.

**Closed** 2017-08-29 17:29 UTC
Labels: enhancement
