### ISSUE TITLE
Eth-Precision Variant Surcharge No Longer Defaults to Zero

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1821] opened 2019-10-24 17:43 UTC
When creating a listing with variants, the surcharge no longer defaults to zero, like it used to. This causes an error when the user tries to save their listing if they haven't manually entered zero into the surcharge fields for each variant combo.

(I confirmed that it auto-fills zero by default in master)

![image](https://user-images.githubusercontent.com/1584275/67511020-0aced380-f664-11e9-8e9b-4f27ec02cebd.png)

**Comment by rmisio** [comment] 2019-10-24 18:45
Well, it wasn't by design that it autofilled in master. It was because protobuf defaults integers to 0 and now that the number is a string, it defaults to an empty string.

We don't really default most other things. We leave it on the user to explicitly enter it otherwise they may gloss over and not even think to add a surcharge when they otherwise want to.

I could put a default of zero back in. Really it's a UX decision on if that's what we want.

**Comment by jjeffryes** [comment] 2019-10-24 19:14
My strong preference is to keep the experience the same, even if it means changing things in the code.

**Comment by rmisio** [comment] 2019-10-24 19:23
Even if the experience you want to match is inconsistent with the bulk of other similar experiences and it wasn't even an intentional experience, just a product of a limitation of the server's serialization lib?

**Comment by jjeffryes** [comment] 2019-10-24 19:26
I think having defaults where they make sense is a good idea, if we don't do that in other places then it'd be nice to fix those other places too.

We could make it a server issue to put those defaults in, if that's better.

**Comment by rmisio** [comment] 2019-10-24 19:32
Ok, if you want me to put this default back in, despite disagreeing because it breaks consistency, I'll do it.

If you want me to put defaults across the board or have the server do it, I am not comfortable with that. I think that would need to involve the UX team. I believe the UX team put a lot of thought on what fields should be required and whether those fields should have defaults. I did my best to follow the specs on that and only couldn't on the surcharge due to a server limitation.

If we're going to change the UX, I think it's a decision that should come from them.

**Comment by jjeffryes** [comment] 2019-10-24 19:33
Just this one, so it stays consistent with the previous UX.

**Comment by rmisio** [comment] 2019-10-24 20:55
fixed via e9df714e24afcad1513ee3f4d0aefc6c804f318b

**Comment by rmisio** [comment] 2019-12-03 19:48
This fix is already merged into `ethereum-master`.

**Closed** 2019-12-04 21:28 UTC
