### ISSUE TITLE
Mouse scroll down in chat message input goes to last line

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#941] opened 2017-09-25 03:06 UTC
v2.0.11 Win 7 64 bits
In a chat message with multiple lines, if user scroll down with mouse middle button (scroll), it always goes to the last (bottom) line. If user wants to edit line 3, he must use up arrow on keyboard to navigate.

![3rd line](https://user-images.githubusercontent.com/10789865/30790896-41534da4-a185-11e7-9487-ec29e25f264f.png)

**Comment by ekerstein** [comment] 2017-09-25 03:23
It worked for me. I tested with both a touchpad and with a mouse and I could scroll through each line.

**Comment by rmisio** [comment] 2017-09-25 16:39
I can't reproduce this on OSX. I'm going to close this one as super low priority. It may only be a Windows issue (or a Win 7 issue) and it doesn't seem super common that a user would be using the scroll wheel to navigate through a chat message.

**Closed by rmisio** 2017-09-25 16:39 UTC
Labels: Low Priority
