### ISSUE TITLE
Create dialog to confirm leaving without saving on Edit Listing page

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#595] opened 2017-07-31 01:22 UTC
There should be a dialog box confirming that user really wants to leave the Edit Listing page without saving (when clicking on close "x" button on top right corner or navigating to other page).

**Comment by rmisio** [comment] 2017-07-31 03:49
closing as duplicate of #104

**Closed by rmisio** 2017-07-31 03:49 UTC
