### ISSUE TITLE
Pressing 'save' in create listing modal doesn't close the modal

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-desktop#194] opened 2016-12-12 23:34 UTC
Not sure if this is a bug, but it's a confusing user experience. Personally, when I hit save, I expect the modal to close.

**Comment by rmisio** [comment] 2016-12-13 00:46
Not a bug. The save process is async and will finish at some point in the future. On our local setups that happens to be really fast, but it's not guaranteed and on remote setups, we'll have bandwidth issues to deal with. Anyhow, the user may be merrily scrolling / reading / updating some part of the form while the save is in progress. If we auto-closed, they could be interrupted from doing something important.

**Comment by drwasho** [comment] 2016-12-14 04:41
> The save process is async and will finish at some point in the future.

Ok that makes sense,

> Anyhow, the user may be merrily scrolling / reading / updating some part of the form while the save is in progress. If we auto-closed, they could be interrupted from doing something important.

This part doesn't make sense. When I hit save, and that's the only button available to me, then my assumption as the user is that this is the button I press when I've finished. The behavior you describe would make sense **if** there were two buttons: `Save` and `Finish`.

When I press save, and it doesn't close, my assumption is that I either didn't press the save button correctly or the client is bugging out and didn't detect the fact that I pressed the button. Either way, I press the button again (which I assume triggers another call, and more resource consumption) or I scroll up and hit 'X'.

@morebrownies your thoughts?

**Comment by morebrownies** [comment] 2016-12-14 19:41
I think we're going to need to find a middle ground on this one. Automatically closing the modal on Save might be the desired experience for some people, but others may Save periodically and expect to close the modal once they're done with their edits. 

@drwasho raises a good point though, clicking Save and then having to scroll to the top to click close is annoying. 

We could consider changing the **Save** button to a **Close** button once the Save action completes. If the user makes more edits to the listing, the button could change back to Save. This would also make it more clear when there are unsaved changes. 

See prototype... (scroll all the way to the bottom and click Save)
https://invis.io/M79QNWLZ3#/211277807_Openbazaar-2-0-Edit-Listing

**Comment by rmisio** [comment] 2016-12-14 20:07
@drwasho If I'm understanding you correctly, what you're suggesting is to close the modal immediately after save is pressed even though the save is in progress and will finish at some point later (few milliseconds later or few seconds in less likely scenarios)?

The problem with that is that if the call fails on the server for some reason, the user would lose all the data from that save. If it was a create, they'd need to start the process over again. This is why we took the middle ground of not preventing the user from leaving the modal while a save is in progress, but we don't want to encourage it either (i.e. make it automatic).

> or I scroll up and hit 'X'

FWIW, you can also click outside the modal or press Esc to exit.

> I think we're going to need to find a middle ground on this one.

@morebrownies I agree. What you propose in the prototype seems like a reasonable approach. It does have some overlap with the status bar messages ('Saving...', 'Listing Grandmas Russian Borscht saved. <view>'). I'm assuming that in the proposed approach, while a save is in progress, the user can still leave the form via Esc keypress or clicking on the overlay? If that's the case, I think we would need to leave the status message so they know the result of the save should they decide to leave. Is that OK?

An alternative is, don't show the status message if they're on the modal, but if they leave while a save is in progress then we'll let them know the status via the bar. There'd be a bit more scope in that approach.

Anyhow, even just leaving the status message as is and integrating the changes in your prototype would be some work and, for consistency would probably need to be applied to the Settings modal as well. If we do decide to go that route, let's prioritize this bug so we know when to tackle it relative to other tasks.

**Comment by rmisio** [comment] 2016-12-14 20:11
@drwasho Sorry for closing so quickly before you could respond.

**Comment by morebrownies** [comment] 2016-12-14 20:35
> FWIW, you can also click outside the modal or press Esc to exit.

Definitely. I think it's safe to assume that not all people will be aware of these shortcuts though. 

> It does have some overlap with the status bar messages ('Saving...', 'Listing Grandmas Russian Borscht saved. ').

Having the status bar message continue to display seems fine to me. The user may scroll back up on the listing modal anyway, so in that case, the status bar message will continue to inform them on the status of the save progress.

> Anyhow, even just leaving the status message as is and integrating the changes in your prototype would be some work and, for consistency would probably need to be applied to the Settings modal as well. 

Agreed. Leaving the status message is should be fine and we would want to replicate this change in Settings too.

> If we do decide to go that route, let's prioritize this bug so we know when to tackle it relative to other tasks.

👍  Paging @jjeffryes

**Comment by jjeffryes** [comment] 2016-12-15 00:52
I'd say we don't need this for milestone 1, but it would be good to get in before we build any other modals that have save buttons, so we don't have extra rework required when we fix this.

**Comment by drwasho** [comment] 2016-12-15 01:03
I like that design @morebrownies @rmisio ... +1

**Comment by jjeffryes** [comment] 2017-02-28 19:49
The linked prototype is now blank, @morebrownies. 

Do we still want to add the changes suggested here, or leave things as-is? @drwasho @rmisio

**Comment by morebrownies** [comment] 2017-02-28 19:56
Amazon S3 is down at the moment. The prototype should be working again as soon as S3 is back up. 

I think we should still do this, but we can layer it in later on.

**Comment by rmisio** [comment] 2017-02-28 21:49
@hoffmabc @jjeffryes Sounds like we need a post full release milestone. Is that something we could get added into the repo?

I think this is a good example of the type of scope we should be deferring if we want to meet the timetable we decide on.

**Comment by jjeffryes** [comment] 2018-05-31 17:20
I think the current state of saving listings has been working and we haven't revisited this issue for over a year, so I'm going to close it.

**Closed by jjeffryes** 2018-05-31 17:20 UTC
Labels: enhancement
