### ISSUE TITLE
Add processing to follow/unfollow buttons on the user page

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#372] opened 2017-02-22 21:04 UTC
The user page should be updated to use the new processing button template on the follow/unfollow button, so it will show the processing spinner when the button is clicked.

**Comment by rmisio** [comment] 2017-02-23 16:24
Closing as dupe of #209.

My main concern here is that the User Card on the User Page should use the common view. Once that's in place, it will already have the functionality.

**Comment by jjeffryes** [comment] 2017-02-23 16:44
I forgot about #209.

Though to be precise, this isn't about the user card, it's about the follow button in the top half of the page.

**Comment by rmisio** [comment] 2017-02-23 17:23
Ah, ok. Let's keep this one open then.

![image](https://cloud.githubusercontent.com/assets/794517/23270729/af1a39da-f9a9-11e6-9160-7f56d64ccd6c.png)

**Closed** 2017-03-22 15:51 UTC
Labels: bug
