### ISSUE TITLE
First listing in 2nd page of search is always selected

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#894] opened 2017-09-16 04:56 UTC
It always displays this black border

![listing](https://user-images.githubusercontent.com/10789865/30509235-1c663e48-9a82-11e7-97c5-8e08be84dcec.png)

**Comment by morebrownies** [comment] 2017-09-20 22:51
Are you still seeing this issue @rhcastilhos? 

I can't reproduce it on my end? What operating system do you use?

**Comment by rhcastilhos** [comment] 2017-09-21 00:52
I see this on v.2.0.11 both on Win7 64 bits and on macOS Sierra 10.12.2

I mean this black line border:

![listing2](https://user-images.githubusercontent.com/10789865/30674081-ee05cabc-9e4d-11e7-81ef-599597e0ac9c.png)

**Comment by morebrownies** [comment] 2017-09-21 16:03
Ok thanks for the details.

The black border should appear when you hit tab to give you a visual indicator of which listing you're currently targeted on.

> However, when you hit Enter, the listing is not opening. So you can't navigate using keyboard on search page.

Hitting enter to open the listing is a good idea. I would expect this action would open the listing as well.

**Comment by rhcastilhos** [comment] 2017-09-23 21:04
Maybe a solution would be select first listing also on 1st page of search results. This way users can hit Tab until they find their desired listing and then hit Enter to visit it.

**Comment by tyler-smith** [comment] 2017-09-23 21:07
Yeah I think having it worked on the first page like it does on subsequent pages, and enter to open would be really nice. I think this was a bug but should be a feature.

**Comment by jjeffryes** [comment] 2017-10-23 18:05
This is the intended behavior, there is code in place to set the focus on the first result.

The bug is that the focus wasn't being applied on the first search.

**Comment by jjeffryes** [comment] 2017-10-23 18:26
@morebrownies to correct this properly, we'd need to allow the listing card to open by hitting the enter key.

Then for consistency, so should the user card, and both should do it everywhere.

That might mean the first listing card in the store should also auto-focus.

And we'd probably want a nicer focus state than the default outline. Other tabbable elements like the user icon should have tabbable focus states too. 

Just a few things to consider. For now I'm going to disable the focus.

**Comment by jjeffryes** [comment] 2018-03-22 19:11
I'm closing this issue, it's part of generally making the app keyboard accessible.

**Closed by jjeffryes** 2018-03-22 19:11 UTC
Labels: Low Priority - cosmetic or non-blocking, bug, enhancement
