### ISSUE TITLE
can't install .rpm

### ISSUE THREAD

**Issue by nurazhar** [OpenBazaar/openbazaar-desktop#1227] opened 2018-02-09 03:54 UTC
Brief Description: 

Operating System (OS and version): fedora 27
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware: 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. 
2. 
3. 

Observed Behavior:

Expected Behavior:

Additional info (links, images, etc go here):

![screenshot from 2018-02-09 11-52-42](https://user-images.githubusercontent.com/31495752/36011074-e72e4500-0d8f-11e8-8a16-25bd0aa81159.png)

**Comment by hegjon** [comment] 2018-03-12 17:35
Duplicate of #985

**Comment by irishpride44** [comment] 2018-03-16 13:29
Compile the Tarball from the source?

https://github.com/OpenBazaar/openbazaar-desktop/archive/v2.1.1.tar.gz

It's a lengthy process like 7 steps on Debian to build a tarball, hopefully it's easier on Fedora.

**Closed** 2018-03-16 16:10 UTC
